version: "3.7"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=StrongPassword!123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  soccer:
    build: src
    ports:
      - "5000:5000"
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose